# Generated by Django 5.1.4 on 2025-01-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbagereport',
            name='status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('RECEIVED', 'Received'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='SENT', max_length=20),
        ),
        migrations.AddField(
            model_name='garbagereport',
            name='zone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
