# Generated by Django 5.1.4 on 2025-01-30 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_garbagereport_status_garbagereport_zone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='garbagereport',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garbagereport',
            name='completion_image',
            field=models.ImageField(blank=True, null=True, upload_to='completion_reports/'),
        ),
        migrations.AddField(
            model_name='garbagereport',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='garbagereport',
            name='worker_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='garbagereport',
            name='status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('RECEIVED', 'Received'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='SENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='garbagereport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.IntegerField(choices=[(1, 'Zone 1'), (2, 'Zone 2'), (3, 'Zone 3'), (4, 'Zone 4'), (5, 'Zone 5'), (6, 'Zone 6'), (7, 'Zone 7'), (8, 'Zone 8'), (9, 'Zone 9'), (10, 'Zone 10'), (11, 'Zone 11'), (12, 'Zone 12'), (13, 'Zone 13'), (14, 'Zone 14'), (15, 'Zone 15'), (16, 'Zone 16')])),
                ('is_worker', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Worker Profile',
                'verbose_name_plural': 'Worker Profiles',
            },
        ),
        migrations.AddField(
            model_name='garbagereport',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to='api.workerprofile'),
        ),
    ]
