# Generated by Django 5.1.4 on 2025-02-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_garbagereport_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbagereport',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='garbage_videos/'),
        ),
    ]
